/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Conexao;
import control.DaoCotacao;
import control.DaoMaterial;
import control.DaoRequisicaoCompra;
import model.Cotacao;
import model.Material;
import model.RequisicaoCompra;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Gabriel Pilan
 */
public class GUI_GerenciarCotacoesDeUmaRequisicao extends javax.swing.JFrame {

    /**
     * Creates new form GUI_CadastrarCotacao
     */
    DefaultTableModel dm = null;
    public static String codigoMaterialSelecionado;
    public static String idRequisicaoCompra;

    public GUI_GerenciarCotacoesDeUmaRequisicao() {
        initComponents();
        jTableCotacaoMaterial.setAutoCreateRowSorter(true);
        jTableMaterialRequisitado.setAutoCreateRowSorter(true);
    }

    private void Filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jTableMaterialRequisitado.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdRequisicao = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterialRequisitado = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCotacaoMaterial = new javax.swing.JTable();
        btnAdicionarMaterialTabelaCotacao = new javax.swing.JButton();
        btnSolicitarCotacao = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCotacaoVencedora = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescricaoMaterial = new javax.swing.JTextArea();
        btnCadastrarMateriais = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnExcluirItemCotacao = new javax.swing.JButton();
        btnConsultarFornecedoresMaterial = new javax.swing.JButton();
        chkAdicionarMaterialCadastrado = new javax.swing.JCheckBox();
        txtCodigoMaterialCadastrado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnInserirNaTabelaCotacaoMaterialCadastrado = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Cotacoes de uma Requisicao");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("ID Requisição de Compra");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabela do(s) Material(is) Requistado(s)");

        jTableMaterialRequisitado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterialRequisitado);

        jLabel3.setText("Tabela dos Itens da Requisicao de Compra e o Valor de suas Respectivas Cotações");

        jTableCotacaoMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Material", "CNPJ do Fornecedor", "Status da Cotacao", "Valor Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCotacaoMaterial);

        btnAdicionarMaterialTabelaCotacao.setText("Adicionar Material Selecionado a Tabela de Cotação");
        btnAdicionarMaterialTabelaCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMaterialTabelaCotacaoActionPerformed(evt);
            }
        });

        btnSolicitarCotacao.setText("Solicitar cotação do item selecionado");
        btnSolicitarCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarCotacaoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar Cotações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCotacaoVencedora.setText("Selecionar uma cotação Vencedora");
        btnCotacaoVencedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotacaoVencedoraActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição do(s) Material(is) não encontrado(s) pelo requerente");

        jTextAreaDescricaoMaterial.setColumns(20);
        jTextAreaDescricaoMaterial.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescricaoMaterial);

        btnCadastrarMateriais.setText("Ir para Cadastro de Materiais");
        btnCadastrarMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMateriaisActionPerformed(evt);
            }
        });

        jLabel5.setText("OU");

        btnExcluirItemCotacao.setText("Excluir Item Selecionado");
        btnExcluirItemCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemCotacaoActionPerformed(evt);
            }
        });

        btnConsultarFornecedoresMaterial.setText("Consultar Fornecedores do Material Selecionado");
        btnConsultarFornecedoresMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFornecedoresMaterialActionPerformed(evt);
            }
        });

        chkAdicionarMaterialCadastrado.setText("Inserir na Tabela um Material Ja Cadastrado");
        chkAdicionarMaterialCadastrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkAdicionarMaterialCadastradoMouseClicked(evt);
            }
        });
        chkAdicionarMaterialCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdicionarMaterialCadastradoActionPerformed(evt);
            }
        });

        txtCodigoMaterialCadastrado.setEnabled(false);

        jLabel6.setText("Codigo do Material");

        btnInserirNaTabelaCotacaoMaterialCadastrado.setText("Inserir na Tabela");
        btnInserirNaTabelaCotacaoMaterialCadastrado.setEnabled(false);
        btnInserirNaTabelaCotacaoMaterialCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirNaTabelaCotacaoMaterialCadastradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(btnCadastrarMateriais)
                                    .addComponent(btnAdicionarMaterialTabelaCotacao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtCodigoMaterialCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnInserirNaTabelaCotacaoMaterialCadastrado))
                                    .addComponent(chkAdicionarMaterialCadastrado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarFornecedoresMaterial))
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirItemCotacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSolicitarCotacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCotacaoVencedora)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarMaterialTabelaCotacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarMateriais)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAdicionarMaterialCadastrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoMaterialCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnInserirNaTabelaCotacaoMaterialCadastrado))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultarFornecedoresMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCotacaoVencedora)
                    .addComponent(btnExcluirItemCotacao)
                    .addComponent(btnSolicitarCotacao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMateriaisActionPerformed
        new GUI_GerenciarMaterial().setVisible(true);
    }//GEN-LAST:event_btnCadastrarMateriaisActionPerformed

    private void btnConsultarFornecedoresMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFornecedoresMaterialActionPerformed
        try {
            if (jTableCotacaoMaterial.getSelectedRow() == -1) {
                throw new Exception("Nao existe nenhum Material selecionado na Tabela");
            }else {
                
                codigoMaterialSelecionado = jTableCotacaoMaterial.getValueAt(jTableCotacaoMaterial.getSelectedRow(), 4).toString();
                new GUI_ConsultarFornecedorMaterial().setVisible(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falha ao Consultar Fornecedor de Material: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnConsultarFornecedoresMaterialActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("GABRIEL", "GABRIEL");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoMaterial = new DaoMaterial(conexao.conectar());
        daoRequisicaoCompra = new DaoRequisicaoCompra(conexao.conectar());
        daoCotacao = new DaoCotacao(conexao.conectar());
        
        String id;
        id = GUI_ConsultarRequisicao.IdRequisicao;
        if(id != null){
        txtIdRequisicao.setText(id);        
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {   
            requisicaoCompra = null;
            if (txtIdRequisicao.getText().isEmpty()) {
                
                throw new Exception("Codigo de Requisicao não foi informado.\n"
                        + "Por favor informar um código de requisicao p/ pesquisa.");
            } else {
                
                requisicaoCompra = daoRequisicaoCompra.consultar(Integer.parseInt(txtIdRequisicao.getText().trim()));
                
                
                if (requisicaoCompra == null) {
                    
                    throw new Exception("Codigo de requisicao informado não existe.\n ");
                } else {
                    //String sqlquery = "SELECT tms.numsolicitacao, tms.codmaterial, tm.nomematerial, tms.qtdematerial from tbl_material tm, tbl_material_solicitado tms where tm.codmaterial = tms.codmaterial";
                    //String sqlquery = "SELECT tbl_material_solicitado.numsolicitacao, tbl_material_solicitado.codmaterial, tbl_material.nomematerial, tbl_material_solicitado.qtdematerial from tbl_material inner join tbl_material_solicitado on tbl_material.codmaterial = tbl_material_solicitado.codmaterial";
                    String sqlquery = "SELECT tms.numsolicitacao, tms.codmaterial, tm.nomematerial, tms.qtdematerial "
                            + "from tbl_material tm, tbl_material_solicitado tms "
                            + "where tms.codmaterial = tm.codmaterial AND tms.numsolicitacao = " + txtIdRequisicao.getText().trim();
                    Statement stmt;
                    ResultSet rs;
                    
                    //Carregando a Requisicao na Tabela 
                    try {
                        stmt = conexao.conectar().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                        rs = stmt.executeQuery(sqlquery);
                        jTableMaterialRequisitado.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch (SQLException ex) {
                        
                        Logger.getLogger(GUI_PesquisarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dm = (DefaultTableModel) jTableMaterialRequisitado.getModel();
                    
                    //Carregando a Descricao do Material nao Encontrado
                    
                    requisicaoCompra = daoRequisicaoCompra.consultar(Integer.parseInt(txtIdRequisicao.getText().trim()));
                    jTextAreaDescricaoMaterial.setText("");
                    jTextAreaDescricaoMaterial.setText(requisicaoCompra.getDescricaoMateriaisNaoEncontrados());
                    
                    //Carregando as Cotacoes Previamente Cadastradas
                    
                    sqlquery = "Select * from tbl_cotacao where NUMSOLICITACAO = " + txtIdRequisicao.getText().trim();
                    
                    try {
                        stmt = conexao.conectar().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                        rs = stmt.executeQuery(sqlquery);
                        jTableCotacaoMaterial.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch (SQLException ex) {
                        
                        Logger.getLogger(GUI_PesquisarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dm = (DefaultTableModel) jTableCotacaoMaterial.getModel();
                    
                }
            }
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Falha ao pesquisar requisicao: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarMaterialTabelaCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMaterialTabelaCotacaoActionPerformed
        try {
            if (jTableMaterialRequisitado.getSelectedRow() == -1) {
                throw new Exception("Nao existe nenhum Material selecionado na Tabela");
            }else {
                String codigo;

                codigo = jTableMaterialRequisitado.getValueAt(jTableMaterialRequisitado.getSelectedRow(), 1).toString();
                
                

                DefaultTableModel model = (DefaultTableModel) jTableCotacaoMaterial.getModel();
                model.addRow(new Object[]{"",txtIdRequisicao.getText(),"","",codigo, 0 ,"Aguardando Resposta do Fornecedor","NAO"});
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falha ao adicionar Material: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarMaterialTabelaCotacaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        cotacao = new Cotacao();
        
        int cont = 0;
        

        boolean verificaFornecedor = true;
        for(cont = 0;cont < jTableCotacaoMaterial.getRowCount();cont++){
            if(jTableCotacaoMaterial.getValueAt(cont , 3).equals("")){
                verificaFornecedor = false;
            }
        }
        
        
        cont = 0;
        if(verificaFornecedor == true){
        for(cont = 0;cont < jTableCotacaoMaterial.getRowCount();cont++){
        boolean novaCotacao = false;
        
        if(jTableCotacaoMaterial.getValueAt(cont , 0).equals("")){
            novaCotacao = true;
        }
        
        
                
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate = LocalDate.now();
        
        cotacao.setNumSolicitacaoCompra(Integer.parseInt(txtIdRequisicao.getText()));
        cotacao.setDataCotacao(dtf.format(localDate));
        cotacao.setCNPJ(jTableCotacaoMaterial.getValueAt(cont , 3).toString());        
        cotacao.setCodMaterial(Integer.parseInt(jTableCotacaoMaterial.getValueAt(cont , 4).toString()));
        cotacao.setPrecoMaterial(Float.parseFloat(jTableCotacaoMaterial.getValueAt(cont , 5).toString()));
        cotacao.setSituacaoCotacao(jTableCotacaoMaterial.getValueAt(cont , 6).toString());
        cotacao.setCotacaoVencedora(jTableCotacaoMaterial.getValueAt(cont, 7).toString().trim());

        if(novaCotacao == true){
            
        Random rand = new Random();
        int numcotacao = rand.nextInt(5000);
        numcotacao += 1;
        cotacao.setNumCotacao(numcotacao);
        daoCotacao.inserir(cotacao);
        }else{
        cotacao.setNumCotacao(Integer.parseInt(jTableCotacaoMaterial.getValueAt(cont , 0).toString()));  
        daoCotacao.alterar(cotacao);
        }
        
        }
        btnBuscarActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Cadastro da(s) Cotacao(oes) " +  " concluido com Sucesso");
       }else{
            JOptionPane.showMessageDialog(null, "Atencao eh necessario preencher o CNPJ do Fornecedor Antes "
                    + "de Gravar sua Cotacao " , "Erro", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirItemCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemCotacaoActionPerformed
        try {
            if (jTableCotacaoMaterial.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Nao existe nenhum material Selecionado na Tabela", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                                
                if(!jTableCotacaoMaterial.getValueAt(jTableCotacaoMaterial.getSelectedRow(),0).toString().equals("")){
                daoCotacao.excluir(Integer.parseInt(jTableCotacaoMaterial.getValueAt(jTableCotacaoMaterial.getSelectedRow(),0).toString()));
                }
                int SelectedRow = jTableCotacaoMaterial.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) jTableCotacaoMaterial.getModel();
                model.removeRow(SelectedRow);
                
               JOptionPane.showMessageDialog(null, "Exclusao da Cotacao Realizada com Sucesso");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falha na remoção do material: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirItemCotacaoActionPerformed

    private void btnSolicitarCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarCotacaoActionPerformed
        
    }//GEN-LAST:event_btnSolicitarCotacaoActionPerformed

    private void btnCotacaoVencedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotacaoVencedoraActionPerformed
        idRequisicaoCompra = txtIdRequisicao.getText();
        new GUI_CotacaoVencedora().setVisible(true);
    }//GEN-LAST:event_btnCotacaoVencedoraActionPerformed

    private void chkAdicionarMaterialCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdicionarMaterialCadastradoActionPerformed
        if(chkAdicionarMaterialCadastrado.isSelected()){
        btnInserirNaTabelaCotacaoMaterialCadastrado.setEnabled(true);
        txtCodigoMaterialCadastrado.setEnabled(true);
        }else{
            btnInserirNaTabelaCotacaoMaterialCadastrado.setEnabled(false);
        txtCodigoMaterialCadastrado.setEnabled(false);
        }
    }//GEN-LAST:event_chkAdicionarMaterialCadastradoActionPerformed

    private void chkAdicionarMaterialCadastradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkAdicionarMaterialCadastradoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAdicionarMaterialCadastradoMouseClicked

    private void btnInserirNaTabelaCotacaoMaterialCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirNaTabelaCotacaoMaterialCadastradoActionPerformed
        material = new Material();
        material = daoMaterial.consultar(Integer.parseInt(txtCodigoMaterialCadastrado.getText()));
        if(material == null){
         JOptionPane.showMessageDialog(null, "Material Nao Encontrado no Sistema" , "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
        int codigo = 0;
        
        codigo = material.getCodMaterial();
            
            DefaultTableModel model = (DefaultTableModel) jTableCotacaoMaterial.getModel();
            model.addRow(new Object[]{"",txtIdRequisicao.getText(),"","",codigo, 0 ,"Aguardando Resposta do Fornecedor","NAO"});
        }
    }//GEN-LAST:event_btnInserirNaTabelaCotacaoMaterialCadastradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_GerenciarCotacoesDeUmaRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_GerenciarCotacoesDeUmaRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_GerenciarCotacoesDeUmaRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_GerenciarCotacoesDeUmaRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_GerenciarCotacoesDeUmaRequisicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarMaterialTabelaCotacao;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarMateriais;
    private javax.swing.JButton btnConsultarFornecedoresMaterial;
    private javax.swing.JButton btnCotacaoVencedora;
    private javax.swing.JButton btnExcluirItemCotacao;
    private javax.swing.JButton btnInserirNaTabelaCotacaoMaterialCadastrado;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSolicitarCotacao;
    private javax.swing.JCheckBox chkAdicionarMaterialCadastrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableCotacaoMaterial;
    private javax.swing.JTable jTableMaterialRequisitado;
    private javax.swing.JTextArea jTextAreaDescricaoMaterial;
    private javax.swing.JTextField txtCodigoMaterialCadastrado;
    private javax.swing.JTextField txtIdRequisicao;
    // End of variables declaration//GEN-END:variables

    private Conexao conexao;
    private Cotacao cotacao;
    private DaoCotacao daoCotacao;
    private RequisicaoCompra requisicaoCompra;
    private DaoRequisicaoCompra daoRequisicaoCompra;
    private Material material;
    private DaoMaterial daoMaterial;
}
